name: Publish to NPM

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.1.0, v0.1.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Test setup process
        run: |
          # Run setup to verify everything works
          npm run setup
          
          # Verify all components are extracted
          if [ ! -d "server" ]; then
            echo "Error: server directory not found"
            exit 1
          fi
          if [ ! -d "admin" ]; then
            echo "Error: admin directory not found"
            exit 1
          fi
          if [ ! -d "user" ]; then
            echo "Error: user directory not found"
            exit 1
          fi
          
          echo "Setup verification completed successfully"
        
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}