name: Release Process

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.1.3, v0.1.4, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Extract version from tag
        id: extract-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Update README badge
        run: |
          # Update the version badge in README.md
          VERSION="${{ steps.extract-version.outputs.VERSION }}"
          sed -i "s/version-[0-9]\+\.[0-9]\+\.[0-9]\+/version-${VERSION}/g" README.md
          
          # Verify the change was made
          grep "version-" README.md
      
      - name: Install dependencies
        run: npm install
      
      - name: Test setup and production process
        run: |
          # Run normal setup with the environment variable to indicate CI mode
          CI=true npm run setup
          
          # Create a CI-specific .env file with a dummy API key after setup
          echo "OPENAI_API_KEY=sk-test1234\nNODE_ENV=test\nPORT=3000" > server/.env
          
          # Make scripts executable
          npm run make-executable
          
          # Test production script in CI mode
          CI=true timeout 10s ./scripts/production.sh || true
          
          # Verify all components are extracted
          if [ ! -d "server" ]; then
            echo "Error: server directory not found"
            exit 1
          fi
          if [ ! -d "admin" ]; then
            echo "Error: admin directory not found"
            exit 1
          fi
          if [ ! -d "user" ]; then
            echo "Error: user directory not found"
            exit 1
          fi
          
          echo "Setup verification completed successfully"
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Commit README changes to main branch
        run: |
          # Save current commit information
          CURRENT_COMMIT=$(git rev-parse HEAD)
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Checkout main branch
          git fetch origin main:main
          git checkout main
          
          # Update the version badge in README.md on main branch
          VERSION="${{ steps.extract-version.outputs.VERSION }}"
          sed -i "s/version-[0-9]\+\.[0-9]\+\.[0-9]\+/version-${VERSION}/g" README.md
          
          git add README.md
          
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update version badge to v${VERSION} [skip ci]"
            git push origin main
          fi
          
          # Return to the original commit
          git checkout ${CURRENT_COMMIT}
